#!/bin/bash
# Sourced by scripts/build-macos-ci.sh (release) and scripts/ci/check-supervisor-bundle.sh
# (the PR gate, with an ad-hoc signature), so the release path is exercised before it
# ships. Packs the managed-sync supervisor into Okilum.app (#1013, design:
# docs/sync-supervisor-shape.md). The caller has `set -Eeuo pipefail`.
#
# The signing values are build configuration, never literals in code:
#   OKILUM_BUNDLE_ID        the app's bundle identifier; the helper's code identifier is
#                           this plus ".sync"
#   OKILUM_SIGNING_TEAM_ID  optional; when set it must match the signing identity's team
SUPERVISOR_NAME="okilum-sync-supervisor"
SUPERVISOR_RELATIVE="Contents/MacOS/$SUPERVISOR_NAME"

# supervisor_team_id IDENTITY -> prints the Team ID of that keychain identity.
# `security find-identity` lists `"Developer ID Application: Name (TEAMID)"`; the hash or
# the full name both select the line. A configured OKILUM_SIGNING_TEAM_ID must agree.
supervisor_team_id() {
    local identity="$1" listing derived configured="${OKILUM_SIGNING_TEAM_ID:-}"
    # A failing `security` is an error. No matching line is not: `grep` exiting 1 must
    # not abort this function under pipefail before the fallback below can run.
    listing="$(security find-identity -v -p codesigning)"
    derived="$(printf '%s\n' "$listing" | grep -F "$identity" \
        | sed -En 's/.*\(([A-Z0-9]{10})\)"[[:space:]]*$/\1/p' | head -1 || true)"
    if [[ -n $derived && -n $configured && $derived != "$configured" ]]; then
        echo "OKILUM_SIGNING_TEAM_ID ($configured) differs from the signing identity's team ($derived)" >&2
        return 1
    fi
    derived="${derived:-$configured}"
    if [[ ! $derived =~ ^[A-Z0-9]{10}$ ]]; then
        echo "cannot determine the Team ID of the signing identity; set OKILUM_SIGNING_TEAM_ID" >&2
        return 1
    fi
    printf '%s\n' "$derived"
}

# supervisor_build TEAM_ID BUNDLE_ID TRIPLE: the values are compiled into the binary and
# become its signature policy (okilum-sync-supervisor::policy).
supervisor_build() {
    OKILUM_SIGNING_TEAM_ID="$1" OKILUM_BUNDLE_ID="$2" \
        cargo build --release --locked --target "$3" -p okilum-sync-supervisor
}

# supervisor_stage APP TARGET_DIR TRIPLE: the helper next to the app executable and the
# static LaunchAgent plist that SMAppService registers (generated by the same Rust code
# the adapter verifies, so the two cannot drift). Writing the plist registers nothing.
supervisor_stage() {
    local app="$1" target="$2" triple="$3"
    install -m 755 "$target/$triple/release/$SUPERVISOR_NAME" "$app/$SUPERVISOR_RELATIVE"
    mkdir -p "$app/Contents/Library/LaunchAgents"
    cargo run --release --locked --target "$triple" -p okilum-sync-controller \
        --example bundled_plist -- "$SUPERVISOR_RELATIVE" "$app/Contents/Library/LaunchAgents"
    plutil -lint "$app"/Contents/Library/LaunchAgents/*.plist
}

# supervisor_sign APP IDENTITY BUNDLE_ID [codesign options...]: must run before the outer
# bundle is signed (inside-out). The identifier is explicit, because the app's policy
# requires exactly BUNDLE_ID.sync of the supervisor.
supervisor_sign() {
    local app="$1" identity="$2" bundle="$3"
    shift 3
    codesign --force --options runtime --identifier "$bundle.sync" "$@" \
        --sign "$identity" "$app/$SUPERVISOR_RELATIVE"
    codesign --verify --strict "$app/$SUPERVISOR_RELATIVE"
}
