#!/usr/bin/env python3
"""Generate distribution notices from cargo-about, or stage the committed notice."""
import argparse
import json
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]


def generate(about_json=None):
    if about_json is None:
        with tempfile.TemporaryDirectory() as directory:
            report = Path(directory) / 'licenses.json'
            subprocess.run(['cargo', 'about', 'generate', '--workspace', '--all-features',
                            '--locked', '--fail', '--format', 'json', '-o', str(report)],
                           cwd=ROOT, check=True)
            return generate(report)
    data = json.loads(Path(about_json).read_text())
    chunks = ['# Third-party notices\n\nOkilum is MIT. The following components retain their own licenses.\n',
              (ROOT / 'licenses/README.md').read_text()]
    assets = sorted((ROOT / 'licenses').glob('*.txt'))
    assets += sorted((ROOT / 'crates/okilum-shell/assets/drawings/fonts').glob('*LICENSE.txt'))
    assets += sorted((ROOT / 'crates/okilum-shell/assets/brand/fonts').glob('*OFL.txt'))
    for path in assets:
        chunks.append(f'## {path.relative_to(ROOT)}\n\n```text\n{path.read_text().strip()}\n```\n')
    chunks.append('## Rust dependencies\n\nGenerated by cargo-about 0.9.2; all workspace features and platforms.\n')
    for license in data['licenses']:
        packages = sorted({f"{u['crate']['name']} {u['crate']['version']}" for u in license['used_by']})
        chunks.append(f"### {license['name']} ({license['id']})\n\nApplies to: {', '.join(packages)}\n\n```text\n{license['text'].strip()}\n```\n")
    text = '\n'.join(chunks)
    (ROOT / 'THIRD_PARTY_NOTICES.md').write_text(
        '\n'.join(line.rstrip() for line in text.splitlines()) + '\n')


def stage(destination):
    destination = Path(destination)
    destination.mkdir(parents=True, exist_ok=True)
    for name in ('LICENSE', 'THIRD_PARTY_NOTICES.md'):
        shutil.copyfile(ROOT / name, destination / name)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--from-json', type=Path, help='Previously generated cargo-about report')
    parser.add_argument('--stage', type=Path, help='Copy committed notices into a bundle')
    args = parser.parse_args()
    if args.stage:
        stage(args.stage)
    else:
        generate(args.from_json)
